route:
  receiver: "mailhog"

receivers:
  - name: "mailhog"
    email_configs:
      - to: "time@exemplo.local"
        from: "alertas@lab.local"
        smarthost: "mailhog:1025"
        require_tls: false
        html: '{{ template "email.default.html" . }}'
