groups:
  - name: infra.rules
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Alvo indisponível"
          description: "O alvo {{ $labels.job }} ({{ $labels.instance }}) está off há mais de 1 minuto."

      - alert: HighContainerCPU
        expr: rate(container_cpu_usage_seconds_total{image!=""}[5m]) > 0.5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Uso alto de CPU por container"
          description: "Container {{ $labels.name }} CPU > 50% (média 5m)."
