global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "alertmanager"
    static_configs:
      - targets: ["alertmanager:9093"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  # node-exporter exposto via network_mode: host
  - job_name: "node-exporter"
    static_configs:
      - targets: ["host.docker.internal:9100"]  # em Linux, use o IP do host (ex.: 172.17.0.1:9100)
